# Generated by Django 2.1.2 on 2018-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='nropuertas',
            field=models.PositiveIntegerField(),
        ),
    ]
