# Generated by Django 2.1.2 on 2018-11-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181101_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='fechapub',
            new_name='fechapublicación',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='nropuertas',
            new_name='númeropuertas',
        ),
    ]
