# Generated by Django 2.1.3 on 2018-11-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181106_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ('color',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ('marca',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=200)),
                ('año', models.DateTimeField()),
                ('slug', models.SlugField(max_length=200)),
                ('descripción', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=15)),
                ('número_Puertas', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_de_Publicación', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Marca')),
            ],
            options={
                'ordering': ('-fecha_de_Publicación',),
            },
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.AlterIndexTogether(
            name='vehiculo',
            index_together={('id', 'slug')},
        ),
    ]
