# Generated by Django 2.1.3 on 2018-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181107_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(),
        ),
    ]
