# Generated by Django 2.1.4 on 2018-12-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181209_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_Lista',
            field=models.ForeignKey(default='asd', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.ListaProducto'),
        ),
    ]
